-- Generated from pg_pinyin--0.1.0.sql
-- Upgrade path: 0.0.2 -> 0.1.0

/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/

CREATE OR REPLACE FUNCTION "pinyin__benchmark_model_target_batch_length"(
	"payload" jsonb, /* pgrx::datum::json::JsonB */
	"model" TEXT /* &str */
) RETURNS bigint /* i64 */
STRICT STABLE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pinyin_benchmark_model_target_batch_length_wrapper';

CREATE OR REPLACE FUNCTION "pinyin__char_target_romanize"(
	"sentence" TEXT, /* &str */
	"query_char_offset" INT, /* i32 */
	"suffix" TEXT DEFAULT '' /* &str */
) RETURNS TEXT /* alloc::string::String */
STRICT STABLE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pinyin_char_target_romanize_wrapper';

CREATE OR REPLACE FUNCTION "pinyin__model_target_debug"(
	"sentence" TEXT, /* &str */
	"query_char_offset" INT, /* i32 */
	"model" TEXT /* &str */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
STRICT STABLE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pinyin_model_target_debug_wrapper';

CREATE OR REPLACE FUNCTION "pinyin__model_target_romanize"(
	"sentence" TEXT, /* &str */
	"query_char_offset" INT, /* i32 */
	"model" TEXT /* &str */
) RETURNS TEXT /* alloc::string::String */
STRICT STABLE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pinyin_model_target_romanize_wrapper';

CREATE OR REPLACE FUNCTION "pinyin__word_romanize_model_text"(
	"origin" TEXT, /* &str */
	"model" TEXT /* &str */
) RETURNS TEXT /* alloc::string::String */
STRICT STABLE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pinyin_word_romanize_model_text_wrapper';

CREATE OR REPLACE FUNCTION "pinyin__word_romanize_model_text"(
	"origin" TEXT, /* &str */
	"suffix" TEXT, /* &str */
	"model" TEXT /* &str */
) RETURNS TEXT /* alloc::string::String */
STRICT STABLE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pinyin_word_romanize_model_text_with_suffix_wrapper';

CREATE OR REPLACE FUNCTION "pinyin__word_romanize_model_tokenizer"(
	"tokenizer_input" anyelement, /* pgrx::datum::anyelement::AnyElement */
	"model" TEXT /* &str */
) RETURNS TEXT /* alloc::string::String */
STRICT STABLE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pinyin_word_romanize_model_tokenizer_wrapper';

CREATE OR REPLACE FUNCTION "pinyin__word_romanize_model_tokenizer"(
	"tokenizer_input" anyelement, /* pgrx::datum::anyelement::AnyElement */
	"suffix" TEXT, /* &str */
	"model" TEXT /* &str */
) RETURNS TEXT /* alloc::string::String */
STRICT STABLE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pinyin_word_romanize_model_tokenizer_with_suffix_wrapper';

CREATE OR REPLACE FUNCTION "pinyin__word_target_debug"(
	"sentence" TEXT, /* &str */
	"query_char_offset" INT, /* i32 */
	"suffix" TEXT DEFAULT '', /* &str */
	"model" TEXT DEFAULT '' /* &str */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
STRICT STABLE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pinyin_word_target_debug_wrapper';

CREATE OR REPLACE FUNCTION "pinyin__word_target_romanize"(
	"sentence" TEXT, /* &str */
	"query_char_offset" INT, /* i32 */
	"suffix" TEXT DEFAULT '', /* &str */
	"model" TEXT DEFAULT '' /* &str */
) RETURNS TEXT /* alloc::string::String */
STRICT STABLE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pinyin_word_target_romanize_wrapper';

CREATE OR REPLACE FUNCTION "pinyin_char_romanize"(
	"origin" TEXT /* &str */
) RETURNS TEXT /* alloc::string::String */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pinyin_char_romanize_wrapper';

CREATE OR REPLACE FUNCTION "pinyin_char_romanize"(
	"origin" TEXT, /* &str */
	"suffix" TEXT /* &str */
) RETURNS TEXT /* alloc::string::String */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pinyin_char_romanize_with_suffix_wrapper';

CREATE OR REPLACE FUNCTION "pinyin_clear_suffix_cache"(
	"suffix" TEXT /* &str */
) RETURNS bool /* bool */
STRICT VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pinyin_clear_suffix_cache_for_suffix_wrapper';

CREATE OR REPLACE FUNCTION "pinyin_clear_suffix_cache"() RETURNS bigint /* i64 */
STRICT VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pinyin_clear_suffix_cache_all_wrapper';

CREATE OR REPLACE FUNCTION "pinyin_model_romanize"(
	"origin" TEXT, /* &str */
	"model" TEXT /* &str */
) RETURNS TEXT /* alloc::string::String */
STRICT STABLE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pinyin_model_romanize_wrapper';

CREATE OR REPLACE FUNCTION "pinyin_model_romanize"(
	"tokenizer_input" anyelement, /* pgrx::datum::anyelement::AnyElement */
	"model" TEXT /* &str */
) RETURNS TEXT /* alloc::string::String */
STRICT STABLE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pinyin_model_romanize_with_tokenizer_wrapper';

CREATE OR REPLACE FUNCTION "pinyin_model_romanize_debug"(
	"origin" TEXT, /* &str */
	"model" TEXT /* &str */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
STRICT STABLE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pinyin_model_romanize_debug_wrapper';

CREATE OR REPLACE FUNCTION "pinyin_regex_phrase_patterns"(
	"value" TEXT /* &str */
) RETURNS TEXT[] /* core::option::Option<alloc::vec::Vec<alloc::string::String>> */
STRICT STABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pinyin_regex_phrase_patterns_default_wrapper';

CREATE OR REPLACE FUNCTION "pinyin_regex_phrase_patterns"(
	"value" TEXT, /* &str */
	"generated_pinyin" bool /* bool */
) RETURNS TEXT[] /* core::option::Option<alloc::vec::Vec<alloc::string::String>> */
STRICT STABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pinyin_regex_phrase_patterns_with_generated_wrapper';

CREATE OR REPLACE FUNCTION "pinyin_word_romanize"(
	"origin" TEXT /* &str */
) RETURNS TEXT /* alloc::string::String */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pinyin_word_romanize_wrapper';

CREATE OR REPLACE FUNCTION "pinyin_word_romanize"(
	"origin" TEXT, /* &str */
	"suffix" TEXT /* &str */
) RETURNS TEXT /* alloc::string::String */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pinyin_word_romanize_with_suffix_wrapper';

CREATE OR REPLACE FUNCTION "pinyin_word_romanize"(
	"tokenizer_input" anyelement /* pgrx::datum::anyelement::AnyElement */
) RETURNS TEXT /* alloc::string::String */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pinyin_word_romanize_with_tokenizer_wrapper';

CREATE OR REPLACE FUNCTION "pinyin_word_romanize"(
	"tokenizer_input" anyelement, /* pgrx::datum::anyelement::AnyElement */
	"suffix" TEXT /* &str */
) RETURNS TEXT /* alloc::string::String */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pinyin_word_romanize_with_tokenizer_and_suffix_wrapper';

CREATE OR REPLACE FUNCTION "pinyin_word_romanize_debug"(
	"origin" TEXT, /* &str */
	"suffix" TEXT DEFAULT '', /* &str */
	"model" TEXT DEFAULT '' /* &str */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
STRICT STABLE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pinyin_word_romanize_debug_wrapper';

CREATE SCHEMA IF NOT EXISTS pinyin;

        CREATE TABLE IF NOT EXISTS pinyin.pinyin_mapping (
          character text PRIMARY KEY,
          pinyin text NOT NULL
        );

        CREATE TABLE IF NOT EXISTS pinyin.pinyin_token (
          character text PRIMARY KEY,
          category smallint NOT NULL CHECK (category IN (1, 2, 3))
        );

        CREATE TABLE IF NOT EXISTS pinyin.pinyin_words (
          word text PRIMARY KEY,
          pinyin text NOT NULL
        );

        CREATE TABLE IF NOT EXISTS pinyin.pinyin_dictionary_meta (
          singleton boolean PRIMARY KEY DEFAULT true CHECK (singleton),
          version bigint NOT NULL DEFAULT 1
        );

        INSERT INTO pinyin.pinyin_dictionary_meta (singleton, version)
        VALUES (true, 1)
        ON CONFLICT (singleton) DO NOTHING;

        CREATE OR REPLACE FUNCTION pinyin.pinyin_dictionary_bump_version()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
          UPDATE pinyin.pinyin_dictionary_meta
          SET version = version + 1
          WHERE singleton;
          RETURN NULL;
        END;
        $$;

        DROP TRIGGER IF EXISTS pinyin_mapping_bump_version ON pinyin.pinyin_mapping;
        CREATE TRIGGER pinyin_mapping_bump_version
        AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON pinyin.pinyin_mapping
        FOR EACH STATEMENT
        EXECUTE FUNCTION pinyin.pinyin_dictionary_bump_version();

        DROP TRIGGER IF EXISTS pinyin_words_bump_version ON pinyin.pinyin_words;
        CREATE TRIGGER pinyin_words_bump_version
        AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON pinyin.pinyin_words
        FOR EACH STATEMENT
        EXECUTE FUNCTION pinyin.pinyin_dictionary_bump_version();

        DROP TRIGGER IF EXISTS pinyin_token_bump_version ON pinyin.pinyin_token;
        CREATE TRIGGER pinyin_token_bump_version
        AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON pinyin.pinyin_token
        FOR EACH STATEMENT
        EXECUTE FUNCTION pinyin.pinyin_dictionary_bump_version();

        INSERT INTO pinyin.pinyin_mapping (character, pinyin)
        VALUES (' ', ' ')
        ON CONFLICT (character) DO NOTHING;

        CREATE TABLE IF NOT EXISTS pinyin.pinyin_model_registry (
          model_name text PRIMARY KEY,
          kind text NOT NULL CHECK (kind IN ('g2pw_onnx', 'g2pm_numpy', 'small_onnx')),
          model_path text NOT NULL,
          tokenizer_path text,
          labels_path text,
          config jsonb NOT NULL DEFAULT '{}'::jsonb,
          enabled boolean NOT NULL DEFAULT true
        );

        CREATE TABLE IF NOT EXISTS pinyin.pinyin_model_meta (
          singleton boolean PRIMARY KEY DEFAULT true CHECK (singleton),
          active_model text REFERENCES pinyin.pinyin_model_registry(model_name),
          version bigint NOT NULL DEFAULT 1
        );

        INSERT INTO pinyin.pinyin_model_meta (singleton, active_model, version)
        VALUES (true, NULL, 1)
        ON CONFLICT (singleton) DO NOTHING;

        CREATE OR REPLACE FUNCTION pinyin.pinyin_model_bump_version()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
          UPDATE pinyin.pinyin_model_meta
          SET version = version + 1
          WHERE singleton;
          RETURN NULL;
        END;
        $$;

        CREATE OR REPLACE FUNCTION pinyin.pinyin_model_meta_set_version()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
          IF NEW.active_model IS DISTINCT FROM OLD.active_model THEN
            NEW.version := OLD.version + 1;
          END IF;
          RETURN NEW;
        END;
        $$;

        DROP TRIGGER IF EXISTS pinyin_model_registry_bump_version ON pinyin.pinyin_model_registry;
        CREATE TRIGGER pinyin_model_registry_bump_version
        AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON pinyin.pinyin_model_registry
        FOR EACH STATEMENT
        EXECUTE FUNCTION pinyin.pinyin_model_bump_version();

        DROP TRIGGER IF EXISTS pinyin_model_meta_set_version ON pinyin.pinyin_model_meta;
        CREATE TRIGGER pinyin_model_meta_set_version
        BEFORE UPDATE ON pinyin.pinyin_model_meta
        FOR EACH ROW
        EXECUTE FUNCTION pinyin.pinyin_model_meta_set_version();


CREATE OR REPLACE FUNCTION "pinyin__seed_embedded_data"() RETURNS bool /* bool */
STRICT VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pinyin_seed_embedded_data_internal_wrapper';

DO $$
        BEGIN
          CREATE DOMAIN pinyin.model_identifier AS text
            CHECK (VALUE IS NOT NULL AND btrim(VALUE) <> '');
        EXCEPTION
          WHEN duplicate_object THEN NULL;
        END
        $$;

        CREATE OR REPLACE FUNCTION public.pinyin_word_romanize(origin text, model pinyin.model_identifier)
        RETURNS text
        LANGUAGE sql
        STABLE
        STRICT
        PARALLEL UNSAFE
        AS $$
          SELECT public.pinyin__word_romanize_model_text(origin, model::text)
        $$;

        CREATE OR REPLACE FUNCTION public.pinyin_word_romanize(
          origin text,
          suffix text,
          model pinyin.model_identifier
        )
        RETURNS text
        LANGUAGE sql
        STABLE
        STRICT
        PARALLEL UNSAFE
        AS $$
          SELECT public.pinyin__word_romanize_model_text(origin, suffix, model::text)
        $$;

        CREATE OR REPLACE FUNCTION public.pinyin_word_romanize(
          tokenizer_input anyelement,
          model pinyin.model_identifier
        )
        RETURNS text
        LANGUAGE sql
        STABLE
        STRICT
        PARALLEL UNSAFE
        AS $$
          SELECT public.pinyin__word_romanize_model_tokenizer(tokenizer_input, model::text)
        $$;

        CREATE OR REPLACE FUNCTION public.pinyin_word_romanize(
          tokenizer_input anyelement,
          suffix text,
          model pinyin.model_identifier
        )
        RETURNS text
        LANGUAGE sql
        STABLE
        STRICT
        PARALLEL UNSAFE
        AS $$
          SELECT public.pinyin__word_romanize_model_tokenizer(tokenizer_input, suffix, model::text)
        $$;

DO $pinyin_regex_phrase$
        BEGIN
          IF to_regtype('pdb.query') IS NOT NULL THEN
            EXECUTE $create_function$
              CREATE OR REPLACE FUNCTION public.pinyin_regex_phrase(
                value text,
                slope integer DEFAULT NULL,
                max_expansions integer DEFAULT NULL,
                generated_pinyin boolean DEFAULT false
              )
              RETURNS pdb.query
              LANGUAGE plpgsql
              STABLE
              PARALLEL SAFE
              AS $function$
              DECLARE
                patterns text[];
              BEGIN
                patterns := public.pinyin_regex_phrase_patterns(value, generated_pinyin);

                IF patterns IS NULL THEN
                  RETURN NULL;
                END IF;

                IF cardinality(patterns) = 0 THEN
                  RETURN pdb.empty();
                END IF;

                IF cardinality(patterns) = 1 THEN
                  RETURN pdb.regex(patterns[1]);
                END IF;

                IF max_expansions IS NOT NULL THEN
                  RETURN pdb.regex_phrase(patterns, COALESCE(slope, 0), max_expansions);
                END IF;

                IF slope IS NOT NULL THEN
                  RETURN pdb.regex_phrase(patterns, slope);
                END IF;

                RETURN pdb.regex_phrase(patterns);
              END;
              $function$;
            $create_function$;
          ELSE
            EXECUTE $create_function$
              CREATE OR REPLACE FUNCTION public.pinyin_regex_phrase(
                value text,
                slope integer DEFAULT NULL,
                max_expansions integer DEFAULT NULL,
                generated_pinyin boolean DEFAULT false
              )
              RETURNS text
              LANGUAGE plpgsql
              STABLE
              PARALLEL SAFE
              AS $function$
              BEGIN
                RAISE EXCEPTION
                  'public.pinyin_regex_phrase requires CREATE EXTENSION pg_search before CREATE EXTENSION pg_pinyin';
              END;
              $function$;
            $create_function$;
          END IF;
        END;
        $pinyin_regex_phrase$;

DROP FUNCTION IF EXISTS public.pinyin_word_romanize_hybrid(text);
        DROP FUNCTION IF EXISTS public.pinyin_word_romanize_hybrid(text, text);
        DROP FUNCTION IF EXISTS public.pinyin_word_romanize_hybrid(anyelement);
        DROP FUNCTION IF EXISTS public.pinyin_word_romanize_hybrid(anyelement, text);

INSERT INTO pinyin.pinyin_model_registry (
          model_name,
          kind,
          model_path,
          tokenizer_path,
          labels_path,
          config,
          enabled
        )
        SELECT
          'bundled_g2pm',
          'g2pm_numpy',
          '/usr/share/postgresql/'
            || (current_setting('server_version_num')::int / 10000)::text
            || '/extension/pg_pinyin/g2pm/manifest.json',
          NULL,
          NULL,
          '{"min_confidence":0.80,"min_margin":0.05,"disable_on_error":true}'::jsonb,
          true
        WHERE NOT EXISTS (
          SELECT 1
          FROM pinyin.pinyin_model_registry
          WHERE kind = 'g2pm_numpy'
            AND model_name <> 'bundled_g2pm'
        )
        ON CONFLICT (model_name) DO UPDATE
        SET kind = EXCLUDED.kind,
            model_path = EXCLUDED.model_path,
            tokenizer_path = EXCLUDED.tokenizer_path,
            labels_path = EXCLUDED.labels_path,
            config = EXCLUDED.config,
            enabled = true;

SELECT public.pinyin__seed_embedded_data();
